
---
env: lfc
component: app
componentType: server

ports:
  - name: tcp
    protocol: TCP
    servicePort: 80
    containerPort: 8080
    appProtocol: http

serviceAccount:
  create: false
  name: "default"

service:
  enabled: true

ingress:
  port: 80

deployment:
  customNodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/capacityType
            operator: In
            values:
              - ON_DEMAND

  replicaCount: 1

  terminationGracePeriodSeconds: 300
  # Resource limits can be tuned according to particular application requirements
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
